### PR TITLE
change repo-path default for release-note generate cmd

### LINKED ISSUE #3444: release-notes (and release-sdk) don't check the remotes when reusing an existing temp dir for repos
#### What happened:

When running `release-notes` with `start-rev` and `end-rev` provided, it was observed that the wrong repo was being cloned/updated. The tooling was using kubernetes/kubernetes instead kubernetes-sigs/promo-tools.  This appears to be happening because there is an existing repo clone in the expected temp directory, however it's for another repository (i.e. k/k). The `cloneOrOpenRepo` function in release-sdk doesn't ensure that the repoPath given is one of the remotes. 

[Slack Thread For Reference](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1706882560702119?thread_ts=1706865207.184349&cid=CJH2GBF7Y)

#### What you expected to happen:

release-notes either provides a descriptive error and directions to clean up the temp dir or it clones to a new temp dir. 

#### How to reproduce it (as minimally and precisely as possible):

Run  'release-notes' with no temp directory on one project. Then run it again on a second project (i.e. it would have a different repo path). 

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by DannyBrito**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR changes repo-path value from release-note generate command when omitted to use `temp/<gh-org>-<gh-repo>` to prevent issue of trying to clone/update incorrect repo in existing `path`.
cc: @jeremyrickard 

#### Which issue(s) this PR fixes:
Fixes #3444

#### Does this PR introduce a user-facing change?

```release-note
change default value of --repo-path flag from release-note generate to use <tmp>/<gh-org>-<gh-repo>
```

### CODE REVIEW

File: cmd/release-notes/generate.go [hunk 1]
```diff
@@ -120,7 +120,7 @@ func addGenerateFlags(subcommand *cobra.Command) {
 	subcommand.PersistentFlags().StringVar(
 		&opts.RepoPath,
 		"repo-path",
-		env.Default("REPO_PATH", filepath.Join(os.TempDir(), "k8s-repo")),
+		env.Default("REPO_PATH", filepath.Join(os.TempDir(), fmt.Sprintf("%s-%s", opts.GithubOrg, opts.GithubRepo))),
```
Comment (xmudrii) [inline cmd/release-notes/generate.go:123]: This is not going to work at all because `opts.GithubOrg` and `opts.GithubRepo` are set after the `repo-path` flag is defaulted. In other words, this is always going to default to `kubernetes-kubernetes`, so the issue is not solved. We need to take another approach here, one option that comes to my mind (but that might not be ideal) is to leave the default value as empty, and then properly default in the `ValidateAndFinish` function.

**Review by xmudrii — CHANGES_REQUESTED** [review]

File: cmd/release-notes/generate.go (hunk 1 above)
Comment (DannyBrito) [reply cmd/release-notes/generate.go]: thanks, forgot to test it with different repo from default

**Review by xmudrii — APPROVED** [review]
Thank you for your contribution and bearing with us, @DannyBrito!
/lgtm
/approve
