### PR TITLE
Include revert PR instead of the reverted one in release notes

### LINKED ISSUE #3966: [script] Generation of release notes picks up reverted PR instead of the PR which reverts it
#### What happened:

We were generating release notes for Kueue v0.10.4 using the script with the following command 

```
> release-notes --org kubernetes-sigs --repo kueue --branch release-0.10 --start-sha c79419eb5b3b0021621805a73bec2ff58c398d8b --end-sha 036b210650d64a60458fbdf45bc320c0803d4294 --dependencies=false --required-author="" --debug
WARN No subcommand specified, running "generate"  
INFO Using output format: markdown                
INFO Gathering release notes                      
DEBU Using authenticated GitHub client             file="github/github.go:217"
INFO Starting to process commit 1 of 7 (14.29%): 036b210650d64a60458fbdf45bc320c0803d4294  file="notes/notes.go:699"
INFO Starting to process commit 2 of 7 (28.57%): f692c87796eb6e7cffb8be3fbc90d9e10c0a457b  file="notes/notes.go:699"
INFO Starting to process commit 3 of 7 (42.86%): 2401fa1a0dcc57c3c17e953a2dd92adb5e67f225  file="notes/notes.go:699"
INFO Starting to process commit 4 of 7 (57.14%): 700426b0438d6d9fc75172ec1228e6c31163f06d  file="notes/notes.go:699"
INFO Starting to process commit 5 of 7 (71.43%): 6e435fccbbe61bdd3658d77a840cc2bf11fb2b2b  file="notes/notes.go:699"
INFO Starting to process commit 6 of 7 (85.71%): 7c52602ba8f8ab00d0b215f6f56a3263c6a11bf4  file="notes/notes.go:699"
INFO Starting to process commit 7 of 7 (100.00%): c79419eb5b3b0021621805a73bec2ff58c398d8b  file="notes/notes.go:699"
DEBU Got PR #4779 for commit: 2401fa1a0dcc57c3c17e953a2dd92adb5e67f225  file="notes/notes.go:803"
INFO PR #4779 contains exclusion (release-note-none)  file="notes/notes.go:812"
DEBU Got PR #4716 for commit: 7c52602ba8f8ab00d0b215f6f56a3263c6a11bf4  file="notes/notes.go:803"
INFO PR #4716 contains exclusion (release-note-none)  file="notes/notes.go:812"
DEBU Got PR #4165 for commit: f692c87796eb6e7cffb8be3fbc90d9e10c0a457b  file="notes/notes.go:803"
INFO PR #4165 seems to contain a release note      file="notes/notes.go:829"
DEBU Got PR #4823 for commit: 036b210650d64a60458fbdf45bc320c0803d4294  file="notes/notes.go:803"
INFO PR #4823 seems to contain a release note      file="notes/notes.go:829"
DEBU Got PR #4732 for commit: 6e435fccbbe61bdd3658d77a840cc2bf11fb2b2b  file="notes/notes.go:803"
INFO PR #4732 contains exclusion (release-note-none)  file="notes/notes.go:812"
DEBU Got PR #4689 for commit: c79419eb5b3b0021621805a73bec2ff58c398d8b  file="notes/notes.go:803"
INFO PR #4689 contains exclusion (release-note-none)  file="notes/notes.go:812"
DEBU Got PR #4777 for commit: 700426b0438d6d9fc75172ec1228e6c31163f06d  file="notes/notes.go:803"
INFO PR #4777 contains exclusion (release-note-none)  file="notes/notes.go:812"
INFO Checking PRs for mapped data                  file="notes/notes.go:297"
INFO Finished gathering release notes in 1.168086917s  file="notes/notes.go:265"
INFO Got 2 release notes, performing rendering     file="release-notes/main.go:51"
INFO Release notes written to file: /tmp/release-notes-3165391239  file="release-notes/main.go:152"
```
The generated notes were:
```
## Changes by Kind

### Bug or Regression

- Fix bug which resulted in under-utilization of the resources in a Cohort.
  Now, when a ClusterQueue is configured with `preemption.reclaimWithinCohort: Any`,
  its resources can be lent out more freely, as we are certain that we can reclaim
  them later. Please see PR #4813 for detailed description of scenario. (#4823, @gabesaba)
- Update FairSharing to be incompatible with ClusterQueue.Preemption.BorrowWithinCohort. Using these parameters together is a no-op, and will be validated against in future releases. This change fixes an edge case which triggered an infinite preemption loop when these two parameters were combined. (#4165, @gabesaba)% 
```
but this is not good, because PR [4165](https://github.com/kubernetes-sigs/kueue/pull/4165) is the PR that was reverted on this branch.  The actual PR which should be reported is [4819](https://github.com/kubernetes-sigs/kueue/pull/4819).

#### What you expected to happen:

The script should corrently pick up the reverting PR which actually even had its note.

#### How to reproduce it (as minimally and precisely as possible):

The steps described above still repro the wrong generation using Kueue release-0.10 branch.

#### Anything else we need to know?:

 We adjusted the notes manually.

### PR DESCRIPTION
**Pull request by IrvingMg**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
As described in #3966, the release notes include the reverted PRs instead of the revert PRs.

#### Which issue(s) this PR fixes:

Fixes #3966 

#### Does this PR introduce a user-facing change?

```release-note
Fix release notes to include the revert PR instead of the reverted one.
```

### CODE REVIEW

File: pkg/notes/notes.go [hunk 1]
```diff
@@ -1136,6 +1136,13 @@ func prsNumForCommitFromMessage(commitMessage string) (prs []int, err error) {
 		prs = append(prs, pr)
 	}
 
+	regex = regexp.MustCompile(`\(#(?P<number>\d+)\)\s*\n\nThis reverts commit`)
```
Comment (mimowo) [inline pkg/notes/notes.go:1139]: This seems to anchor the message produced by the "git revert" command; https://github.com/git/git/blob/9d22ac51228304102deb62f30c3ecba6377e1237/sequencer.c#L2366

File: pkg/notes/notes.go [hunk 2]
```diff
@@ -1136,6 +1136,13 @@ func prsNumForCommitFromMessage(commitMessage string) (prs []int, err error) {
...
+
+	pr = prForRegex(regex, commitMessage)
+	if pr != 0 {
+		prs = append(prs, pr)
```
Comment (mimowo) [inline pkg/notes/notes.go:1143]: This is adding a new pr onto the list, and so it is not immediately clear to me, why this fixes the issue?

File: pkg/notes/notes.go (hunk 1 above)
Comment (IrvingMg) [reply pkg/notes/notes.go:1139]: Correct. I've added the `\(#(?P<number>\d+)\)\s*\n\n` part so that we can retrieve the last PR number that appears in the commit message

File: pkg/notes/notes.go (hunk 2 above)
Comment (IrvingMg) [reply pkg/notes/notes.go:1143]: If I understood correctly, the function [prsNumForCommitFromMessage](https://github.com/kubernetes/release/blob/9a9572f7c48f637de8499a201fb8e3ff52f8d4ba/pkg/notes/notes.go#L1122) retrieves all the PR numbers included in the commit message. Then, later in the [notesForCommit](https://github.com/kubernetes/release/blob/9a9572f7c48f637de8499a201fb8e3ff52f8d4ba/pkg/notes/notes.go#L815) function, we iterate over the list of PRs until we find one with a valid release note. Once a valid note is found, we stop the iteration and ignore the remaining PRs.

Currently, revert commits—which contain multiple PR numbers in the message—are handled as regular squashed commits, and the PR number retrieved is the first one that appears. By adding this regex, we prepend the last PR number from the message to the PRs list. So if that PR has a release note, the notesForCommit function will retrieve it and stop, ignoring the rest.

Comment (mimowo) [reply pkg/notes/notes.go:1143]: I see, thanks for the explanation.

**Comment by mimowo** [comment]
LGTM
/assign @saschagrunert 
PTAL

File: pkg/notes/notes.go (hunk 1 above)
Comment (BenTheElder) [reply pkg/notes/notes.go:1139]: not new to this PR, but it would be helpful to use descriptive names (and comments!) instead of repeatedly using the `regex` variable to do different unrelated things.

**Review by saschagrunert — APPROVED** [review]
