### PR TITLE
Default USER_AT_DOMAIN in release::docker::release().

### LINKED ISSUE #461: ERROR: (gcloud.config.set) argument VALUE: Must be specified.
The cross-build job is broken, seemingly due to a recent change in releaselib.sh:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/3849

```
I1113 22:06:02.994] push-build.sh::release::docker::release(): /usr/bin/gcloud config set account
I1113 22:06:03.375] ERROR: (gcloud.config.set) argument VALUE: Must be specified.
I1113 22:06:03.375] Usage: gcloud config set SECTION/PROPERTY VALUE [optional flags]
I1113 22:06:03.375]   optional flags may be  --help | --installation
I1113 22:06:03.375] 
I1113 22:06:03.375] For detailed information on this command and its flags, run:
I1113 22:06:03.376]   gcloud config set --help
I1113 22:06:03.415] 
I1113 22:06:03.419] 
I1113 22:06:03.421] Signal ERR caught!
I1113 22:06:03.424] 
I1113 22:06:03.426] Traceback (line function script):
I1113 22:06:03.426] 948 release::docker::release /var/lib/jenkins/workspace/ci-kubernetes-cross-build/go/src/k8s.io/release/lib/releaselib.sh
I1113 22:06:03.427] 201 main ../release/push-build.sh
I1113 22:06:03.429] 
I1113 22:06:03.432] Exiting...
```

### PR DESCRIPTION
**Pull request by david-mcmahon**
Maintain backward compatibility for DOMAIN_NAME in push-build.sh and add --domain-name flag to man page.

Fixes #461

### CODE REVIEW

File: lib/releaselib.sh [hunk 1]
```diff
@@ -947,7 +947,7 @@ release::docker::release () {
   fi
   
   # Always reset back to $USER
```
Comment (cblecker) [inline lib/releaselib.sh]: This comment doesn't seem to make sense anymore.

File: lib/releaselib.sh [hunk 2]
```diff
@@ -947,7 +947,7 @@ release::docker::release () {
...
-  logrun $GCLOUD config set account $USER_AT_DOMAIN
+  logrun $GCLOUD config set account ${USER_AT_DOMAIN:-$USER@$DOMAIN_NAME}
```
Comment (cblecker) [inline lib/releaselib.sh]: Would it be prudent to quote this, like: `"${USER_AT_DOMAIN:-${USER}@${DOMAIN_NAME}}"`.. gcloud is expecting exactly one value argument

**Comment by david-mcmahon** [comment]
`DOMAIN_NAME` wasn't set anywhere but in `anago` so I don't know where it's coming from when called from test-infra code (couldn't find anything there either).  Either way, this PR now defaults it and also adds visibility in the man page.`

File: lib/releaselib.sh (hunk 2 above)
Comment (david-mcmahon) [reply lib/releaselib.sh]: Done.

**Comment by david-mcmahon** [comment]
Submitting to unblock broken cross builds.
